name: 'Hi from Wim'
description: 'Greet the people of KBC'
inputs:
  names:
    description: 'Names of the people to greet'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Print Greeting
      run: |
        echo "Hello, ${{ inputs.names }}!"
      shell: bash
